---
# Playbook for 1.) creating a file, and 2.) removing the file.

- name: Create file, verify that it's there, and then delete it.
  hosts: all

  tasks:
  - name: Ensure first that the file doesn't exist
    #ansible.builtin.file:
    #  path: /tmp/love.txt
    #  state: absent
    stat: path=/tmp/love.txt
    register: stat
  - name: Whether or not the file is there
    when: stat.stat.exists
    debug: msg="File exists"
  - name: Whether or not the file is there
    when: not stat.stat.exists
    debug: msg="File does NOT exist"

  - name: Create the file.
    ansible.builtin.shell:
      cmd: touch /tmp/love.txt

  - name: List the file.
    ansible.builtin.shell:
      cmd: ls /tmp
    register: ls
  - debug:
      var: ls.stdout_lines

  - name: Remove the file.
    ansible.builtin.shell:
      cmd: rm /tmp/love.txt


#- name: Play number 2
#  hosts: all
#  tasks:
#  - name: Show available facts for the system
#    ansible.builtin.debug:
#      var: ansible_facts
...
